apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    app: podinfo
  ports:
    - name: http  # Nome da porta
      protocol: TCP
      port: 3000  # Porta externa
      targetPort: 8083  # Porta do container
      nodePort: 30080
  type: NodePort  # Expondo a porta