apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: default
spec:
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8083
      nodePort: 30080
  type: NodePort
