gitops-runtime:
  global:
    codefresh:
      accountId: 67e539dfc07898db1fe68984
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
