apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: default #{{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: http  # Nome da porta
      protocol: TCP
      port: {{ .Values.service.port }}  # Porta externa 7000
      targetPort: {{ .Values.service.targetPort }}  # Porta do container
  type: {{ .Values.service.type }}  # Expondo a porta 9898